name: Linux CI

on:
  push:
    tags:
      - "v*.*"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ['8.10.1']
        cabal: ['3.4.0.0']
        
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
        
    - name: Freeze
      run: cabal freeze

    - name: Cache ~/.cabal/store
      uses: actions/cache@v1
      with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
    
    - name: Build binary
      run: |
          mkdir dist
          cabal install --install-method=copy --overwrite-policy=always --installdir=dist
   
    - name: zip files
      run: tar cvfj fuzzy.tar dist/*
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: fuzzy.tar
