name: Linux CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['8.10.1']
        cabal: ['3.4.0.0']
        
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
        
    - name: Freeze
      run: cabal freeze

    - name: Cache ~/.cabal/store
      uses: actions/cache@v1
      with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
    
    - name: Build binary
      run: |
          mkdir dist
          cabal install exe:stan --install-method=copy --overwrite-policy=always --installdir=dist
    
    - if: matrix.os == 'windows-latest'
      name: Set extension to .exe on Windows
      run: echo "::set-env name=EXT::.exe"

    - name: Set binary path name
      run: echo "::set-env name=BINARY_PATH::./dist/stan${{ env.EXT }}"
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: /dist
